### PR TITLE
Fix error:Cannot read property 'setMap' of undefined

### PR DESCRIPTION
**Pull request by wmeler**
Without this I can't make simple marker example work.

### CODE REVIEW

**Comment by imink** [comment]
thx @wmeler, just wondering the previous version has no such problem.

**Comment by wmeler** [comment]
@imink I don't know how it should work, but setMap(null) was introduced in https://github.com/fullstackreact/google-maps-react/pull/23
- I have no idea if it was needed.

**Comment by RobertSheaO** [comment]
You'll notice a few lines below this `if( this.marker )` check is performed for `componentWillUnmount`, I believe this is the proper fix, tried it locally. Can this get merged in to the official branch? Thank you!

**Comment by rojobuffalo** [comment]
Just confirming that this is broken for me too.

**Comment by stboehme** [comment]
broken for me too :(

**Comment by rojobuffalo** [comment]
This line is where the error kicks off for me:
https://github.com/fullstackreact/google-maps-react/blob/master/src/components/Marker.js#L29

In the built code, that `if (this.marker)` condition is missing in `componentDidUpdate`.

**Pull request merged**
