### PR TITLE
Updated peer dependencies to support React 18

### PR DESCRIPTION
**Pull request by kkarimi**
per the [previous PR that bumped to 17](https://github.com/fullstackreact/google-maps-react/pull/516)

### CODE REVIEW

**Comment by kkarimi** [comment]
@auser and others please have a look, thanks

**Comment by ahmad-ali14** [comment]
+1 for this

**Comment by GeorgeBellTMH** [comment]
Please publish to npm

**Comment by timoteialbu** [comment]
Thanks for all your work on this library @auser! Any chance you could get the new React 18 version published to npm? Anything I can do to help?

**Comment by iamibrahimriaz** [comment]
Any Update About Publishing to NPM?

**Comment by chamal-perera-19** [comment]
Any update on this publishing to NPM please ? @kkarimi @auser please let us know. I am getting dependency error when installing from the npm, due to the old package.

**Comment by chamal-perera-19** [comment]
Any update on this publishing to NPM please ? @kkarimi @auser please let us know. I am getting dependency error when installing from the npm, due to the old package.

**Comment by krustevgeorgi** [comment]
Please publish to registry plssssssss

**Pull request merged**
