### PR TITLE
Fix for always setting null to window.google

### PR DESCRIPTION
**Pull request by Aourin**
https://github.com/fullstackreact/google-maps-react/issues/10

### CODE REVIEW

**Comment by auser** [comment]
Thanks!

**Comment by Aourin** [comment]
np, i needed this haha.

**Comment by Aourin** [comment]
what is your release cycle/time?

**Comment by auser** [comment]
I've pushed it just now to npm (1.0.17)

**Comment by Aourin** [comment]
dat spead.

**Pull request merged**
