### PR TITLE
add mapTypeId to prop types for customization

### PR DESCRIPTION
**Pull request by annaboeri**
I am trying to use this package for a project and I am having trouble changing the default map view from roadmap to satellite view. When I added the mapTypeId into the Map.propTypes object in the index.js file, and changed the mapTypeId to "satellite"  in my project, I was able to change the default settings.

### CODE REVIEW

**Comment by DomVinyard** [comment]
can we get this merged?

**Comment by annaboeri** [comment]
Hey Dom - In your map component, if you set the mapTypeControl to true, you can customize the mapType (not sure what you're trying to do but this worked for me:)

        mapTypeControl={true} 
        mapType="satellite"

**Comment by ruimigueldp** [comment]
hey @annaboeri , can we change mapType dynamically?

**Comment by ruimigueldp** [comment]
Nevermind, I made it :D

**Pull request closed without merging**
