### PR TITLE
Circle support

### PR DESCRIPTION
**Pull request by ryanoboril**
I've tried a few of the existing pull requests for this functionality and they did not work for me.  I have re-added the functionality myself in the hopes that this can be merged.  I have included a screenshot and some example code in the README.  Let me know what else needs to be done to get this in.

### CODE REVIEW

**Comment by miliu99** [comment]
This Circle component works, however, it appears it's missing the componentWillReceiveProps event handling, so that when center changes it doesn't redraw. I have to refresh the browser to make it redraw.

**Comment by miliu99** [comment]
This works great. Thank you very much! Why not release it?

**Comment by ryanoboril** [comment]
I don't have merge access for this repo, so all I can do is submit a pull request and wait for it to be reviewed.

@auser Is anyone available to review this?

**Comment by auser** [comment]
Thanks! It’s perfect

**Comment by ryanoboril** [comment]
No problem, thanks for making this module.  It's great!

**Comment by miliu99** [comment]
Just tried and it seems the lastest 2.0.2 doesn't work.

**Comment by ryanoboril** [comment]
@auser `Circle` does not appear in `dist`, was there a successful prod rebuild prior to npm publish?  If i pull the repo into my `node_modules` it works fine, but with the 2.0.2 npm there is no transpiled `dist/components/Circle.js` file and it looks like the transpiled `index.js` in `dist` does not export it.  It doesn't look like the latest.

**Comment by miliu99** [comment]
Sorry, I spoke a little too early...it is strange that it works fine in dev mode, but not in production mode - I got "Minified react error #130".

**Pull request merged**
